### PR TITLE
Create an npm leaderboard project with webpack

### PR DESCRIPTION
**Pull request by MMGGYY66**
Create an npm leaderboard project with webpack

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Eldimardash,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted a project, which appears that _ESLint_ is not properly setup, and hence, _ESLint_ checks not showing on your Pull Request. Kindly ensure that **all** required linters are properly configured and are passing! Kindly request for another code review when this is done.

**ESLint not showing:**
image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by MMGGYY66** [comment]
Hi Robert Loterh,
I installed eslint properly and tested it in my project. please check your review again.
you can see this picture to make sure:
https://www.dropbox.com/s/h79berac0ch6xp3/Screenshot%202023-01-31%20at%2008.29.38.png?dl=0

**Comment by rloterh** [comment]
> Hi Robert Loterh, I installed eslint properly and tested it in my project. please check your review again. you can see this picture to make sure: https://www.dropbox.com/s/h79berac0ch6xp3/Screenshot%202023-01-31%20at%2008.29.38.png?dl=0

In the process of responding I noticed you've resolved this issue. Congrats!

Cheers! 😃

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @MMGGYY66 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️

- [ ] you shouldn't leave the MIT license empty with placeholders please make sure to add your information to the MIT license so that it will be valid 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MMGGYY66** [comment]
hello @youmari ,
I have called you many times to explain where to add mit licence. I added it already in the readme.md file. please check this:
https://www.dropbox.com/s/b77ifj6eabty710/Screenshot%202023-01-31%20at%2009.51.09.png?dl=0

https://www.dropbox.com/s/cjfhnjeolvklnp1/Screenshot%202023-01-31%20at%2009.51.33.png?dl=0

**Comment by Gambit142** [comment]
Hi @MMGGYY66, what @youmari is explaining is that you should edit your MIT.md file and fill in your information. In the MIT.md file, replace [YOUR NAME] caption with your actual name and replace all captions of [APP TYPE] with the name of this repository. 👍

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @MMGGYY66 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- Use of `Webpack` to bundle JavaScript codes ✔️ 
- Configured `Webpack` correctly ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️

- Kindly edit your _**MIT.md**_ file and fill in your information. In the _**MIT.md**_ file, replace **_[YOUR NAME]_** caption with your actual name and replace all captions of **_[APP TYPE]_** with the name of this repository. 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by TadesseDev — APPROVED** [review]
### Hi @MMGGYY66 
### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697




## Highlights
 - [ ] Good job making the changes requested by the previous code reviewers. ✅
 - [ ]  Correct GitHub Flow. ✅
 - [ ]  Good commit history. ✅
 - [ ]  All linters passed ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
> hello @youmari , I have called you many times to explain where to add mit licence. I added it already in the readme.md file. please check this: https://www.dropbox.com/s/b77ifj6eabty710/Screenshot%202023-01-31%20at%2009.51.09.png?dl=0
> 
> https://www.dropbox.com/s/cjfhnjeolvklnp1/Screenshot%202023-01-31%20at%2009.51.33.png?dl=0

@Gambit142 Thanks for explaining to @MMGGYY66  I was already off sorry for that @MMGGYY66

**Pull request merged**
